# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FileTab.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1222, 867)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.splitter_2 = QtWidgets.QSplitter(Form)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.frame = QtWidgets.QFrame(self.splitter_2)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self.frame)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(3)
        self.splitter.setObjectName("splitter")
        self.frame_4 = QtWidgets.QFrame(self.splitter)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setMinimumSize(QtCore.QSize(0, 15))
        self.label.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.ResourceList = QtWidgets.QListView(self.frame_4)
        self.ResourceList.setMinimumSize(QtCore.QSize(310, 0))
        self.ResourceList.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.ResourceList.setObjectName("ResourceList")
        self.verticalLayout_5.addWidget(self.ResourceList)
        self.frame_5 = QtWidgets.QFrame(self.splitter)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setMinimumSize(QtCore.QSize(0, 15))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.MaterialSelectorView = QtWidgets.QListView(self.frame_5)
        self.MaterialSelectorView.setMinimumSize(QtCore.QSize(310, 0))
        self.MaterialSelectorView.setObjectName("MaterialSelectorView")
        self.verticalLayout_2.addWidget(self.MaterialSelectorView)
        self.frame_2 = QtWidgets.QFrame(self.splitter)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.ResourceBinding = QtWidgets.QStackedWidget(self.frame_2)
        self.ResourceBinding.setMinimumSize(QtCore.QSize(550, 150))
        self.ResourceBinding.setObjectName("ResourceBinding")
        self.verticalLayout.addWidget(self.ResourceBinding)
        self.horizontalLayout.addWidget(self.splitter)
        self.MaterialListView = QtWidgets.QFrame(self.splitter_2)
        self.MaterialListView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.MaterialListView.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.MaterialListView.setLineWidth(1)
        self.MaterialListView.setObjectName("MaterialListView")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.MaterialListView)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.MaterialHeaderView = QtWidgets.QStackedWidget(self.MaterialListView)
        self.MaterialHeaderView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.MaterialHeaderView.setObjectName("MaterialHeaderView")
        self.verticalLayout_3.addWidget(self.MaterialHeaderView)
        self.frame_3 = QtWidgets.QFrame(self.splitter_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ParameterView = QtWidgets.QStackedWidget(self.frame_3)
        self.ParameterView.setMinimumSize(QtCore.QSize(0, 100))
        self.ParameterView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ParameterView.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ParameterView.setLineWidth(1)
        self.ParameterView.setObjectName("ParameterView")
        self.verticalLayout_4.addWidget(self.ParameterView)
        self.verticalLayout_6.addWidget(self.splitter_2)

        self.retranslateUi(Form)
        self.MaterialHeaderView.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Resources"))
        self.label_2.setText(_translate("Form", "Materials"))
        self.label_3.setText(_translate("Form", "Resource Bindings"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
