# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MaterialHeader.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(606, 191)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.MaterialDetailsView = QtWidgets.QFrame(Form)
        self.MaterialDetailsView.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MaterialDetailsView.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MaterialDetailsView.setObjectName("MaterialDetailsView")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.MaterialDetailsView)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.splitter = QtWidgets.QSplitter(self.MaterialDetailsView)
        self.splitter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.splitter.setLineWidth(1)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setHandleWidth(2)
        self.splitter.setObjectName("splitter")
        self.frame_2 = QtWidgets.QFrame(self.splitter)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.MaterialLinkNameEditor = QtWidgets.QFrame(self.frame_2)
        self.MaterialLinkNameEditor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MaterialLinkNameEditor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MaterialLinkNameEditor.setObjectName("MaterialLinkNameEditor")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.MaterialLinkNameEditor)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.MaterialLinkNameEditor)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.MaterialLinkName = QtWidgets.QLineEdit(self.MaterialLinkNameEditor)
        self.MaterialLinkName.setObjectName("MaterialLinkName")
        self.horizontalLayout_3.addWidget(self.MaterialLinkName)
        self.MaterialHash = QtWidgets.QLabel(self.MaterialLinkNameEditor)
        self.MaterialHash.setMinimumSize(QtCore.QSize(80, 0))
        self.MaterialHash.setObjectName("MaterialHash")
        self.horizontalLayout_3.addWidget(self.MaterialHash)
        self.ShaderTitle = QtWidgets.QLabel(self.MaterialLinkNameEditor)
        self.ShaderTitle.setObjectName("ShaderTitle")
        self.horizontalLayout_3.addWidget(self.ShaderTitle)
        self.ShaderHash = QtWidgets.QLineEdit(self.MaterialLinkNameEditor)
        self.ShaderHash.setInputMethodHints(QtCore.Qt.ImhExclusiveInputMask)
        self.ShaderHash.setObjectName("ShaderHash")
        self.horizontalLayout_3.addWidget(self.ShaderHash)
        self.SkinId = QtWidgets.QLineEdit(self.MaterialLinkNameEditor)
        self.SkinId.setInputMethodHints(QtCore.Qt.ImhExclusiveInputMask)
        self.SkinId.setObjectName("SkinId")
        self.horizontalLayout_3.addWidget(self.SkinId)
        self.verticalLayout_2.addWidget(self.MaterialLinkNameEditor)
        self.frame_14 = QtWidgets.QFrame(self.frame_2)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.SurfaceDirectionLabel = QtWidgets.QLabel(self.frame_14)
        self.SurfaceDirectionLabel.setObjectName("SurfaceDirectionLabel")
        self.horizontalLayout_14.addWidget(self.SurfaceDirectionLabel)
        self.SurfaceDirection = QtWidgets.QSpinBox(self.frame_14)
        self.SurfaceDirection.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.SurfaceDirection.setMinimum(-2147483647)
        self.SurfaceDirection.setMaximum(2147483647)
        self.SurfaceDirection.setProperty("value", 0)
        self.SurfaceDirection.setDisplayIntegerBase(16)
        self.SurfaceDirection.setObjectName("SurfaceDirection")
        self.horizontalLayout_14.addWidget(self.SurfaceDirection)
        self.StrayUnknownLabel = QtWidgets.QLabel(self.frame_14)
        self.StrayUnknownLabel.setObjectName("StrayUnknownLabel")
        self.horizontalLayout_14.addWidget(self.StrayUnknownLabel)
        self.StrayUnknown = QtWidgets.QSpinBox(self.frame_14)
        self.StrayUnknown.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.StrayUnknown.setMaximum(255)
        self.StrayUnknown.setObjectName("StrayUnknown")
        self.horizontalLayout_14.addWidget(self.StrayUnknown)
        self.UnknownOffsetLabel = QtWidgets.QLabel(self.frame_14)
        self.UnknownOffsetLabel.setObjectName("UnknownOffsetLabel")
        self.horizontalLayout_14.addWidget(self.UnknownOffsetLabel)
        self.UnknownOffset = QtWidgets.QSpinBox(self.frame_14)
        self.UnknownOffset.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.UnknownOffset.setMinimum(-2147483647)
        self.UnknownOffset.setMaximum(2147483647)
        self.UnknownOffset.setDisplayIntegerBase(16)
        self.UnknownOffset.setObjectName("UnknownOffset")
        self.horizontalLayout_14.addWidget(self.UnknownOffset)
        self.verticalLayout_2.addWidget(self.frame_14)
        self.frame = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.UnknownTitle = QtWidgets.QLabel(self.frame)
        self.UnknownTitle.setObjectName("UnknownTitle")
        self.verticalLayout.addWidget(self.UnknownTitle)
        self.frame_15 = QtWidgets.QFrame(self.frame)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.unk0 = QtWidgets.QSpinBox(self.frame_15)
        self.unk0.setMaximum(255)
        self.unk0.setObjectName("unk0")
        self.horizontalLayout.addWidget(self.unk0)
        self.unk1 = QtWidgets.QSpinBox(self.frame_15)
        self.unk1.setMaximum(255)
        self.unk1.setObjectName("unk1")
        self.horizontalLayout.addWidget(self.unk1)
        self.unk2 = QtWidgets.QSpinBox(self.frame_15)
        self.unk2.setMaximum(255)
        self.unk2.setObjectName("unk2")
        self.horizontalLayout.addWidget(self.unk2)
        self.unk3 = QtWidgets.QSpinBox(self.frame_15)
        self.unk3.setMaximum(255)
        self.unk3.setObjectName("unk3")
        self.horizontalLayout.addWidget(self.unk3)
        self.unk4 = QtWidgets.QSpinBox(self.frame_15)
        self.unk4.setMaximum(255)
        self.unk4.setObjectName("unk4")
        self.horizontalLayout.addWidget(self.unk4)
        self.unk5 = QtWidgets.QSpinBox(self.frame_15)
        self.unk5.setMaximum(255)
        self.unk5.setObjectName("unk5")
        self.horizontalLayout.addWidget(self.unk5)
        self.unk6 = QtWidgets.QSpinBox(self.frame_15)
        self.unk6.setMaximum(255)
        self.unk6.setObjectName("unk6")
        self.horizontalLayout.addWidget(self.unk6)
        self.unk7 = QtWidgets.QSpinBox(self.frame_15)
        self.unk7.setMaximum(255)
        self.unk7.setObjectName("unk7")
        self.horizontalLayout.addWidget(self.unk7)
        self.unk8 = QtWidgets.QSpinBox(self.frame_15)
        self.unk8.setMaximum(255)
        self.unk8.setObjectName("unk8")
        self.horizontalLayout.addWidget(self.unk8)
        self.unk9 = QtWidgets.QSpinBox(self.frame_15)
        self.unk9.setMaximum(255)
        self.unk9.setObjectName("unk9")
        self.horizontalLayout.addWidget(self.unk9)
        self.unk10 = QtWidgets.QSpinBox(self.frame_15)
        self.unk10.setMaximum(255)
        self.unk10.setObjectName("unk10")
        self.horizontalLayout.addWidget(self.unk10)
        self.unk11 = QtWidgets.QSpinBox(self.frame_15)
        self.unk11.setMaximum(255)
        self.unk11.setObjectName("unk11")
        self.horizontalLayout.addWidget(self.unk11)
        self.verticalLayout.addWidget(self.frame_15)
        self.frame_16 = QtWidgets.QFrame(self.frame)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.unk12 = QtWidgets.QSpinBox(self.frame_16)
        self.unk12.setMaximum(255)
        self.unk12.setObjectName("unk12")
        self.horizontalLayout_2.addWidget(self.unk12)
        self.unk13 = QtWidgets.QSpinBox(self.frame_16)
        self.unk13.setMaximum(255)
        self.unk13.setObjectName("unk13")
        self.horizontalLayout_2.addWidget(self.unk13)
        self.unk14 = QtWidgets.QSpinBox(self.frame_16)
        self.unk14.setMaximum(255)
        self.unk14.setObjectName("unk14")
        self.horizontalLayout_2.addWidget(self.unk14)
        self.unk15 = QtWidgets.QSpinBox(self.frame_16)
        self.unk15.setMaximum(255)
        self.unk15.setObjectName("unk15")
        self.horizontalLayout_2.addWidget(self.unk15)
        self.unk16 = QtWidgets.QSpinBox(self.frame_16)
        self.unk16.setMaximum(255)
        self.unk16.setObjectName("unk16")
        self.horizontalLayout_2.addWidget(self.unk16)
        self.unk17 = QtWidgets.QSpinBox(self.frame_16)
        self.unk17.setMaximum(255)
        self.unk17.setObjectName("unk17")
        self.horizontalLayout_2.addWidget(self.unk17)
        self.unk18 = QtWidgets.QSpinBox(self.frame_16)
        self.unk18.setMaximum(255)
        self.unk18.setObjectName("unk18")
        self.horizontalLayout_2.addWidget(self.unk18)
        self.unk19 = QtWidgets.QSpinBox(self.frame_16)
        self.unk19.setMaximum(255)
        self.unk19.setObjectName("unk19")
        self.horizontalLayout_2.addWidget(self.unk19)
        self.unk20 = QtWidgets.QSpinBox(self.frame_16)
        self.unk20.setMaximum(255)
        self.unk20.setObjectName("unk20")
        self.horizontalLayout_2.addWidget(self.unk20)
        self.unk21 = QtWidgets.QSpinBox(self.frame_16)
        self.unk21.setMaximum(255)
        self.unk21.setObjectName("unk21")
        self.horizontalLayout_2.addWidget(self.unk21)
        self.unk22 = QtWidgets.QSpinBox(self.frame_16)
        self.unk22.setMaximum(255)
        self.unk22.setObjectName("unk22")
        self.horizontalLayout_2.addWidget(self.unk22)
        self.unk23 = QtWidgets.QSpinBox(self.frame_16)
        self.unk23.setMaximum(255)
        self.unk23.setObjectName("unk23")
        self.horizontalLayout_2.addWidget(self.unk23)
        self.verticalLayout.addWidget(self.frame_16)
        self.verticalLayout_4.addWidget(self.splitter)
        self.verticalLayout_3.addWidget(self.MaterialDetailsView)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Material Name"))
        self.MaterialHash.setText(_translate("Form", "matNameHash"))
        self.ShaderTitle.setText(_translate("Form", "Shader Id"))
        self.ShaderHash.setInputMask(_translate("Form", "HHHHHHHH"))
        self.ShaderHash.setText(_translate("Form", "00000000"))
        self.SkinId.setInputMask(_translate("Form", "HHHHHHHH"))
        self.SkinId.setText(_translate("Form", "00000000"))
        self.SurfaceDirectionLabel.setText(_translate("Form", "Surface Direction"))
        self.StrayUnknownLabel.setText(_translate("Form", "Stray Unknown"))
        self.UnknownOffsetLabel.setText(_translate("Form", "Unknown Offset"))
        self.UnknownTitle.setText(_translate("Form", "Unknown Parameters"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
