# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MaterialResources.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(694, 186)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.ResourceBinding = QtWidgets.QFrame(Form)
        self.ResourceBinding.setMinimumSize(QtCore.QSize(0, 155))
        self.ResourceBinding.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ResourceBinding.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ResourceBinding.setObjectName("ResourceBinding")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.ResourceBinding)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self.ResourceBinding)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(2)
        self.splitter.setObjectName("splitter")
        self.ResourceListView = QtWidgets.QListView(self.splitter)
        self.ResourceListView.setMinimumSize(QtCore.QSize(220, 0))
        self.ResourceListView.setObjectName("ResourceListView")
        self.ResourceEdit = QtWidgets.QFrame(self.splitter)
        self.ResourceEdit.setMinimumSize(QtCore.QSize(315, 150))
        self.ResourceEdit.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ResourceEdit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ResourceEdit.setObjectName("ResourceEdit")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.ResourceEdit)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ResourceType = QtWidgets.QLabel(self.ResourceEdit)
        self.ResourceType.setMinimumSize(QtCore.QSize(200, 26))
        self.ResourceType.setMaximumSize(QtCore.QSize(200, 26))
        self.ResourceType.setObjectName("ResourceType")
        self.verticalLayout.addWidget(self.ResourceType)
        self.frame_8 = QtWidgets.QFrame(self.ResourceEdit)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 44))
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 44))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.ResourceUnknownsLabel = QtWidgets.QLabel(self.frame_8)
        self.ResourceUnknownsLabel.setMinimumSize(QtCore.QSize(70, 26))
        self.ResourceUnknownsLabel.setMaximumSize(QtCore.QSize(60, 26))
        self.ResourceUnknownsLabel.setObjectName("ResourceUnknownsLabel")
        self.horizontalLayout_7.addWidget(self.ResourceUnknownsLabel)
        self.resourceUnk0 = QtWidgets.QSpinBox(self.frame_8)
        self.resourceUnk0.setMinimumSize(QtCore.QSize(43, 20))
        self.resourceUnk0.setMaximumSize(QtCore.QSize(43, 20))
        self.resourceUnk0.setMaximum(255)
        self.resourceUnk0.setObjectName("resourceUnk0")
        self.horizontalLayout_7.addWidget(self.resourceUnk0)
        self.resourceUnk1 = QtWidgets.QSpinBox(self.frame_8)
        self.resourceUnk1.setMinimumSize(QtCore.QSize(43, 20))
        self.resourceUnk1.setMaximumSize(QtCore.QSize(43, 20))
        self.resourceUnk1.setMaximum(255)
        self.resourceUnk1.setObjectName("resourceUnk1")
        self.horizontalLayout_7.addWidget(self.resourceUnk1)
        self.resourceUnk2 = QtWidgets.QSpinBox(self.frame_8)
        self.resourceUnk2.setMinimumSize(QtCore.QSize(30, 20))
        self.resourceUnk2.setMaximumSize(QtCore.QSize(45, 20))
        self.resourceUnk2.setMaximum(255)
        self.resourceUnk2.setObjectName("resourceUnk2")
        self.horizontalLayout_7.addWidget(self.resourceUnk2)
        self.resourceUnk3 = QtWidgets.QSpinBox(self.frame_8)
        self.resourceUnk3.setMinimumSize(QtCore.QSize(60, 20))
        self.resourceUnk3.setMaximumSize(QtCore.QSize(60, 20))
        self.resourceUnk3.setMinimum(-2147483647)
        self.resourceUnk3.setMaximum(2147483647)
        self.resourceUnk3.setObjectName("resourceUnk3")
        self.horizontalLayout_7.addWidget(self.resourceUnk3)
        self.verticalLayout.addWidget(self.frame_8)
        self.frame_7 = QtWidgets.QFrame(self.ResourceEdit)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 46))
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 46))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.frame_7)
        self.label_5.setMinimumSize(QtCore.QSize(60, 26))
        self.label_5.setMaximumSize(QtCore.QSize(60, 26))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.ResourceIx = QtWidgets.QSpinBox(self.frame_7)
        self.ResourceIx.setMinimumSize(QtCore.QSize(50, 20))
        self.ResourceIx.setMaximumSize(QtCore.QSize(20, 16777215))
        self.ResourceIx.setMaximum(429467296)
        self.ResourceIx.setObjectName("ResourceIx")
        self.horizontalLayout_6.addWidget(self.ResourceIx)
        self.ResourceLabel = QtWidgets.QLabel(self.frame_7)
        self.ResourceLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.ResourceLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ResourceLabel.setObjectName("ResourceLabel")
        self.horizontalLayout_6.addWidget(self.ResourceLabel)
        self.horizontalLayout_6.setStretch(0, 4)
        self.horizontalLayout_6.setStretch(1, 4)
        self.verticalLayout.addWidget(self.frame_7)
        self.horizontalLayout.addWidget(self.splitter)
        self.gridLayout.addWidget(self.ResourceBinding, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.ResourceType.setText(_translate("Form", "Resource Type"))
        self.ResourceUnknownsLabel.setText(_translate("Form", "Unknowns"))
        self.label_5.setText(_translate("Form", "Resource"))
        self.ResourceLabel.setText(_translate("Form", "TextLabel"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
